language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - python -m pytest tests/ --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
